version: '3.8'

services:
  your-app:
    image: ssh2usb:latest
    container_name: ssh2usb
    working_dir: /APP
    restart: always
    privileged: true               # 需要特权模式访问 USB 设备
    volumes:
      - /path/to/dir:/APP/config   # 配置文件
      - /dev/bus/usb:/dev/bus/usb  # 挂载 USB 设备 必须要有这个
    ports:
      - "8067:8023"
      - "8068:8024"
    environment:
      - TZ=Asia/Shanghai
      - ENV=production
